### ISSUE TITLE
Error adding account to wallet

### ISSUE THREAD

**Issue by hhthedude** [aaroncox/vessel#110]
This is the error I see when trying to add an account to the wallet and I open the Developers Tools:

Uncaught Error: getaddrinfo ENOTFOUND steemd.steemit.com steemd.steemit.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

What might be causing this?

**Comment by Jolly-Pirate** [comment]
steemd.steemit.com is decommisioned, use api.steemit.com. Also, use the latest version of Vessel.

**Comment by hhthedude** [comment]
I thought I had the most recent version - 0.2.0, is there a later version?

Where all does 'steemd' need to be replaced with 'api'?

**Comment by Jolly-Pirate** [comment]
In the Settings, set the Steem RPC Node to `https://api.steemit.com`, if it doesn't connect, try `https://anyx.io`
