### ISSUE TITLE
sh: 1: concurrently: not found

### ISSUE THREAD

**Issue by bidetaggle** [aaroncox/vessel#112]
`npm run-script build`
```

> vessel@0.2.8 build /home/axel/Desktop/vessel
> concurrently "npm run build-main" "npm run build-renderer"

sh: 1: concurrently: not found
```

And also this when I enter the fresh downloaded git directory:
```
warning: CRLF will be replaced by LF in app/semantic-ui/themes/default/assets/fonts/icons.eot.                                                                                  
The file will have its original line endings in your working directory.
```
and if I do `git status`:
```
	modified:   app/semantic-ui/themes/default/assets/fonts/icons.eot
	modified:   app/semantic-ui/themes/default/assets/fonts/icons.ttf
```

Really strange, it's the first time that I see that from a git clone

**Comment by aaroncox** [comment]
Did your `npm install` work after you cloned it down? 

`concurrently` is a dev dependency and should be installed during that process.

I'm not sure why the line endings for the icons are acting strange - that might be a side effect of what seems like the dependencies not being installed correctly.

**Comment by bidetaggle** [comment]
Indeed, I think I forgot to do `npm install`, but here is the output:
```

> rabin-bindings@1.7.4 install /home/axel/Desktop/vessel/node_modules/rabin-bindings
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.3.0
prebuild-install info looking for local prebuild @ prebuilds/rabin-bindings-v1.7.4-node-v72-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /home/axel/.npm/_prebuilds/https-github.com-develar-rabin-bindings-releases-download-v1.7.4-rabin-bindings-v1.7.4-node-v72-linux-x64.tar.gz
prebuild-install http request GET https://github.com/develar/rabin-bindings/releases/download/v1.7.4/rabin-bindings-v1.7.4-node-v72-linux-x64.tar.gz
prebuild-install http 404 https://github.com/develar/rabin-bindings/releases/download/v1.7.4/rabin-bindings-v1.7.4-node-v72-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=12.10.0 runtime=node arch=x64 platform=linux)
make: Entering directory '/home/axel/Desktop/vessel/node_modules/rabin-bindings/build'
  CXX(target) Release/obj.target/rabin-bindings/bindings.o
In file included from ../node_modules/nan/nan_converters.h:67:0,
                 from ../node_modules/nan/nan.h:202,
                 from ../bindings.cc:2:
../node_modules/nan/nan_converters_43_inl.h: In static member function ‘static Nan::imp::ToFactoryBase<v8::Boolean>::return_t Nan::imp::ToFactory<v8::Boolean>::convert(v8::Local<v8::Value>)’:
../node_modules/nan/nan_converters_43_inl.h:18:69: warning: ‘v8::MaybeLocal<v8::Boolean> v8::Value::ToBoolean(v8::Local<v8::Context>) const’ is deprecated: ToBoolean can never throw. Use Local version. [-Wdeprecated-declarations]
       val->To ## TYPE(v8::Isolate::GetCurrent()->GetCurrentContext())          \
                                                                     ^
../node_modules/nan/nan_converters_43_inl.h:22:1: note: in expansion of macro ‘X’
 X(Boolean)
 ^
In file included from /home/axel/.cache/node-gyp/12.10.0/include/node/v8-internal.h:14:0,
                 from /home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:25,
                 from /home/axel/.cache/node-gyp/12.10.0/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:51,
                 from ../bindings.cc:2:
/home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:2537:59: note: declared here
                 V8_WARN_UNUSED_RESULT MaybeLocal<Boolean> ToBoolean(
                                                           ^
/home/axel/.cache/node-gyp/12.10.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../node_modules/nan/nan_converters.h:67:0,
                 from ../node_modules/nan/nan.h:202,
                 from ../bindings.cc:2:
../node_modules/nan/nan_converters_43_inl.h: In static member function ‘static Nan::imp::ValueFactoryBase<bool>::return_t Nan::imp::ToFactory<bool>::convert(v8::Local<v8::Value>)’:
../node_modules/nan/nan_converters_43_inl.h:37:57: warning: ‘v8::Maybe<bool> v8::Value::BooleanValue(v8::Local<v8::Context>) const’ is deprecated: BooleanValue can never throw. Use Isolate version. [-Wdeprecated-declarations]
   return val->NAME ## Value(isolate->GetCurrentContext());                     \
                                                         ^
../node_modules/nan/nan_converters_43_inl.h:40:1: note: in expansion of macro ‘X’
 X(bool, Boolean)
 ^
In file included from /home/axel/.cache/node-gyp/12.10.0/include/node/v8-internal.h:14:0,
                 from /home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:25,
                 from /home/axel/.cache/node-gyp/12.10.0/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:51,
                 from ../bindings.cc:2:
/home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:2575:51: note: declared here
                 V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                   ^
/home/axel/.cache/node-gyp/12.10.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../node_modules/nan/nan_new.h:189:0,
                 from ../node_modules/nan/nan.h:203,
                 from ../bindings.cc:2:
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::Function>::return_t Nan::imp::Factory<v8::Function>::New(Nan::FunctionCallback, v8::Local<v8::Value>)’:
../node_modules/nan/nan_implementation_12_inl.h:105:32: error: no matching function for call to ‘v8::Function::New(v8::Isolate*&, void (&)(const v8::FunctionCallbackInfo<v8::Value>&), v8::Local<v8::Object>&)’
                           , obj));
                                ^
In file included from /home/axel/.cache/node-gyp/12.10.0/include/node/node.h:63:0,
                 from ../node_modules/nan/nan.h:51,
                 from ../bindings.cc:2:
/home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:4138:31: note: candidate: static v8::MaybeLocal<v8::Function> v8::Function::New(v8::Local<v8::Context>, v8::FunctionCallback, v8::Local<v8::Value>, int, v8::ConstructorBehavior, v8::SideEffectType)
   static MaybeLocal<Function> New(
                               ^
/home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:4138:31: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘v8::Local<v8::Context>’
In file included from ../node_modules/nan/nan_new.h:189:0,
                 from ../node_modules/nan/nan.h:203,
                 from ../bindings.cc:2:
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::StringObject>::return_t Nan::imp::Factory<v8::StringObject>::New(v8::Local<v8::String>)’:
../node_modules/nan/nan_implementation_12_inl.h:337:37: error: no matching function for call to ‘v8::StringObject::New(v8::Local<v8::String>&)’
   return v8::StringObject::New(value).As<v8::StringObject>();
                                     ^
In file included from /home/axel/.cache/node-gyp/12.10.0/include/node/node.h:63:0,
                 from ../node_modules/nan/nan.h:51,
                 from ../bindings.cc:2:
/home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:5394:23: note: candidate: static v8::Local<v8::Value> v8::StringObject::New(v8::Isolate*, v8::Local<v8::String>)
   static Local<Value> New(Isolate* isolate, Local<String> value);
                       ^
/home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:5394:23: note:   candidate expects 2 arguments, 1 provided
In file included from ../node_modules/nan/nan_new.h:189:0,
                 from ../node_modules/nan/nan.h:203,
                 from ../bindings.cc:2:
../node_modules/nan/nan_implementation_12_inl.h:337:58: error: expected primary-expression before ‘>’ token
   return v8::StringObject::New(value).As<v8::StringObject>();
                                                          ^
../node_modules/nan/nan_implementation_12_inl.h:337:60: error: expected primary-expression before ‘)’ token
   return v8::StringObject::New(value).As<v8::StringObject>();
                                                            ^
In file included from ../bindings.cc:2:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’:
../node_modules/nan/nan.h:840:60: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, func, argc, argv);
                                                            ^
In file included from ../node_modules/nan/nan.h:51:0,
                 from ../bindings.cc:2:
/home/axel/.cache/node-gyp/12.10.0/include/node/node.h:174:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/axel/.cache/node-gyp/12.10.0/include/node/node.h:93:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from ../bindings.cc:2:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’:
../node_modules/nan/nan.h:855:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, symbol, argc, argv);
                                                              ^
In file included from ../node_modules/nan/nan.h:51:0,
                 from ../bindings.cc:2:
/home/axel/.cache/node-gyp/12.10.0/include/node/node.h:167:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/axel/.cache/node-gyp/12.10.0/include/node/node.h:93:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from ../bindings.cc:2:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’:
../node_modules/nan/nan.h:870:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, method, argc, argv);
                                                              ^
In file included from ../node_modules/nan/nan.h:51:0,
                 from ../bindings.cc:2:
/home/axel/.cache/node-gyp/12.10.0/include/node/node.h:160:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/axel/.cache/node-gyp/12.10.0/include/node/node.h:93:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from ../bindings.cc:2:0:
../node_modules/nan/nan.h: In constructor ‘Nan::Utf8String::Utf8String(v8::Local<v8::Value>)’:
../node_modules/nan/nan.h:916:53: error: no matching function for call to ‘v8::Value::ToString()’
       v8::Local<v8::String> string = from->ToString();
                                                     ^
In file included from /home/axel/.cache/node-gyp/12.10.0/include/node/node.h:63:0,
                 from ../node_modules/nan/nan.h:51,
                 from ../bindings.cc:2:
/home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:2541:44: note: candidate: v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                            ^
/home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:2541:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/axel/.cache/node-gyp/12.10.0/include/node/v8-internal.h:14:0,
                 from /home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:25,
                 from /home/axel/.cache/node-gyp/12.10.0/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:51,
                 from ../bindings.cc:2:
/home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:2557:31: note: candidate: v8::Local<v8::String> v8::Value::ToString(v8::Isolate*) const
                 Local<String> ToString(Isolate* isolate) const);
                               ^
/home/axel/.cache/node-gyp/12.10.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
/home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:2557:31: note:   candidate expects 1 argument, 0 provided
                 Local<String> ToString(Isolate* isolate) const);
                               ^
/home/axel/.cache/node-gyp/12.10.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../bindings.cc:2:0:
../node_modules/nan/nan.h:926:74: error: no matching function for call to ‘v8::String::WriteUtf8(char*&, int, int, const int&)’
         length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                                                                          ^
In file included from /home/axel/.cache/node-gyp/12.10.0/include/node/node.h:63:0,
                 from ../node_modules/nan/nan.h:51,
                 from ../bindings.cc:2:
/home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:2751:7: note: candidate: int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const
   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
       ^
/home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:2751:7: note:   no known conversion for argument 1 from ‘char*’ to ‘v8::Isolate*’
In file included from ../bindings.cc:2:0:
../node_modules/nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’:
../node_modules/nan/nan.h:1484:5: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
     ));
     ^
In file included from ../node_modules/nan/nan.h:51:0,
                 from ../bindings.cc:2:
/home/axel/.cache/node-gyp/12.10.0/include/node/node.h:174:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/axel/.cache/node-gyp/12.10.0/include/node/node.h:93:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from ../bindings.cc:2:0:
../node_modules/nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(const char*, const v8::Local<v8::Value>&)’:
../node_modules/nan/nan.h:1538:64: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     New(persistentHandle)->Set(New(key).ToLocalChecked(), value);
                                                                ^
In file included from /home/axel/.cache/node-gyp/12.10.0/include/node/v8-internal.h:14:0,
                 from /home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:25,
                 from /home/axel/.cache/node-gyp/12.10.0/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:51,
                 from ../bindings.cc:2:
/home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:3372:22: note: declared here
                 bool Set(Local<Value> key, Local<Value> value));
                      ^
/home/axel/.cache/node-gyp/12.10.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../bindings.cc:2:0:
../node_modules/nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(const v8::Local<v8::String>&, const v8::Local<v8::Value>&)’:
../node_modules/nan/nan.h:1544:42: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     New(persistentHandle)->Set(key, value);
                                          ^
In file included from /home/axel/.cache/node-gyp/12.10.0/include/node/v8-internal.h:14:0,
                 from /home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:25,
                 from /home/axel/.cache/node-gyp/12.10.0/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:51,
                 from ../bindings.cc:2:
/home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:3372:22: note: declared here
                 bool Set(Local<Value> key, Local<Value> value));
                      ^
/home/axel/.cache/node-gyp/12.10.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../bindings.cc:2:0:
../node_modules/nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(uint32_t, const v8::Local<v8::Value>&)’:
../node_modules/nan/nan.h:1550:44: warning: ‘bool v8::Object::Set(uint32_t, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     New(persistentHandle)->Set(index, value);
                                            ^
In file included from /home/axel/.cache/node-gyp/12.10.0/include/node/v8-internal.h:14:0,
                 from /home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:25,
                 from /home/axel/.cache/node-gyp/12.10.0/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:51,
                 from ../bindings.cc:2:
/home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:3381:22: note: declared here
                 bool Set(uint32_t index, Local<Value> value));
                      ^
/home/axel/.cache/node-gyp/12.10.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../bindings.cc:2:0:
../node_modules/nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const char*) const’:
../node_modules/nan/nan.h:1556:61: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         New(persistentHandle)->Get(New(key).ToLocalChecked()));
                                                             ^
In file included from /home/axel/.cache/node-gyp/12.10.0/include/node/v8-internal.h:14:0,
                 from /home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:25,
                 from /home/axel/.cache/node-gyp/12.10.0/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:51,
                 from ../bindings.cc:2:
/home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:3425:51: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
                                                   ^
/home/axel/.cache/node-gyp/12.10.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../bindings.cc:2:0:
../node_modules/nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const v8::Local<v8::String>&) const’:
../node_modules/nan/nan.h:1562:55: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     return scope.Escape(New(persistentHandle)->Get(key));
                                                       ^
In file included from /home/axel/.cache/node-gyp/12.10.0/include/node/v8-internal.h:14:0,
                 from /home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:25,
                 from /home/axel/.cache/node-gyp/12.10.0/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:51,
                 from ../bindings.cc:2:
/home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:3425:51: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
                                                   ^
/home/axel/.cache/node-gyp/12.10.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../bindings.cc:2:0:
../node_modules/nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(uint32_t) const’:
../node_modules/nan/nan.h:1567:57: warning: ‘v8::Local<v8::Value> v8::Object::Get(uint32_t)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     return scope.Escape(New(persistentHandle)->Get(index));
                                                         ^
In file included from /home/axel/.cache/node-gyp/12.10.0/include/node/v8-internal.h:14:0,
                 from /home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:25,
                 from /home/axel/.cache/node-gyp/12.10.0/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:51,
                 from ../bindings.cc:2:
/home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:3429:51: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Value> Get(uint32_t index));
                                                   ^
/home/axel/.cache/node-gyp/12.10.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
In file included from /usr/include/c++/5/cassert:43:0,
                 from /home/axel/.cache/node-gyp/12.10.0/include/node/node_object_wrap.h:26,
                 from ../node_modules/nan/nan.h:53,
                 from ../bindings.cc:2:
../node_modules/nan/nan_object_wrap.h: In destructor ‘virtual Nan::ObjectWrap::~ObjectWrap()’:
../node_modules/nan/nan_object_wrap.h:24:25: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
     assert(persistent().IsNearDeath());
                         ^
In file included from ../node_modules/nan/nan.h:2365:0,
                 from ../bindings.cc:2:
../node_modules/nan/nan_object_wrap.h: In member function ‘void Nan::ObjectWrap::MakeWeak()’:
../node_modules/nan/nan_object_wrap.h:67:34: warning: ‘void v8::PersistentBase<T>::MarkIndependent() [with T = v8::Object]’ is deprecated: Weak objects are always considered independent. Use TracedGlobal when trying to use EmbedderHeapTracer. Use a strong handle when trying to keep an object alive. [-Wdeprecated-declarations]
     persistent().MarkIndependent();
                                  ^
In file included from /home/axel/.cache/node-gyp/12.10.0/include/node/v8-internal.h:14:0,
                 from /home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:25,
                 from /home/axel/.cache/node-gyp/12.10.0/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:51,
                 from ../bindings.cc:2:
/home/axel/.cache/node-gyp/12.10.0/include/node/v8.h:567:22: note: declared here
       V8_INLINE void MarkIndependent());
                      ^
/home/axel/.cache/node-gyp/12.10.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
In file included from /usr/include/c++/5/cassert:43:0,
                 from /home/axel/.cache/node-gyp/12.10.0/include/node/node_object_wrap.h:26,
                 from ../node_modules/nan/nan.h:53,
                 from ../bindings.cc:2:
../node_modules/nan/nan_object_wrap.h: In static member function ‘static void Nan::ObjectWrap::WeakCallback(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’:
../node_modules/nan/nan_object_wrap.h:124:26: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
     assert(wrap->handle_.IsNearDeath());
                          ^
rabin-bindings.target.mk:111: recipe for target 'Release/obj.target/rabin-bindings/bindings.o' failed
make: *** [Release/obj.target/rabin-bindings/bindings.o] Error 1
make: Leaving directory '/home/axel/Desktop/vessel/node_modules/rabin-bindings/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-62-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/axel/Desktop/vessel/node_modules/rabin-bindings
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm WARN eslint-plugin-flowtype-errors@3.3.6 requires a peer of eslint@>=4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-flowtype-errors@3.3.6 requires a peer of flow-bin@>=0.57.3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.2.0 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.2.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@1.0.1 (node_modules/7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rabin-bindings@1.7.4 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rabin-bindings@1.7.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/axel/.npm/_logs/2019-09-16T13_09_57_789Z-debug.log
warning: CRLF will be replaced by LF in app/semantic-ui/themes/default/assets/fonts/icons.eot.                                                                                  
The file will have its original line endings in your working directory.
```

The icons thing is popping as soon as I enter in the repository with a single `cd` straight after having typed `git clone ...`, I think it's not even related to the first issue

**Comment by aaroncox** [comment]
You will probably have to use an older version of nodejs to get the `npm install` to work. I think Vessel was developed somewhere around nodejs v0.8, and from the looks of the logs you're using v0.12.

**Comment by bidetaggle** [comment]
Well, I abandon then, too much troubles

**Comment by aaroncox** [comment]
To be blunt, if you can't be bothered to use something like `nvm` and be capable of switching nodejs versions, then indeed it's probably too much trouble for you.

**Comment by bidetaggle** [comment]
Yes it is too much trouble. My personal projects work on the latest version of node (and if not, I fix it), all the node projects that I found on git worked with this version until now. nvm is one more tweak that I will have to remember when I gonna come back to another code later, yet another readme to spend time on (if not more?).
The version is not even noticed in the readme, I just feel like it's just the beginning to make vessel works properly and I will bump into another unexpected issue right after.
I might come later and contribute on the readme but for now I'd rather spend my time on something else, I was just curious to see an actual desktop wallet for steem.
