### ISSUE TITLE
Hangs on account add if it times out

### ISSUE THREAD

**Issue by onthax** [aaroncox/vessel#69]
Had an issue yesterday where i could access steemit.com, steemd.com etc fine but on a fresh install of vessell when i tried to add an account it sat their spinning the wheel indefinitely

Dev mode showed.

bundle.js:1 Unhandled rejection Error: connect ETIMEDOUT 34.225.89.14:443 at Object.exports._errnoException (util.js:1050:11) at exports._exceptionWithHostPort (util.js:1073:20) at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)

Working today, but would be nice for it to error and popping up with a human readable message

PS: loving the new features!

**Comment by aaroncox** [comment]
I've been getting a few reports of this happening and have a work around until I have a more permanent option to change nodes in place. It's happening when the node you've specified to connect to is unavailable.

If you open the Developers Tools (View -> Developers Tools), and then navigate to the Console tab, there's an area on the bottom that allows you to enter a command. The following command will reset the preferences of the wallet, which also resets the default node. You will lose any saved exchange memo fields with this command, so if you had any previously, be sure to set them again. 

```
localStorage.setItem('reduxPersist:preferences', '{"steemd_node":"https://wallet.steem.ws"}')
```

This command sets the preferences object manually and resets the wallet to use https://wallet.steem.ws (which is also the default). 

From there, you can either refresh the wallet (CTRL +R) or just restart Vessel for the changes to take effect.

**Comment by onthax** [comment]
Sounds good,

Thanks for the quick response.

**Comment by fraenk** [comment]
ah, thanks @aaroncox, I was looking for how to change the node manually!
