### ISSUE TITLE
Can't Connect Account to Vessel Wallet

### ISSUE THREAD

**Issue by SaipanDamashii** [aaroncox/vessel#88]
When I launch Vessel and try to connect my Steemit account to it, after I enter all my information and press the green button, it just loads forever and nothing happens.  I've tried it again and again multiple times and it always just gets stuck with the loading circle thing.  Is there anything I can do to fix this and get past that?

**Comment by aaroncox** [comment]
It sounds like the server you're connecting to isn't responding. Do you have the newest (0.2.7) version? If so, you should be able to change servers to one that's working.

**Comment by GATOQSECOMIO** [comment]
same problem here.
I used "toogle developer tool" with the following result:

>bundle.js:359  action SET_PREFERECE @ 19:52:05.559
bundle.js:1 Unhandled rejection Error: unexpected server response (200)
    at ClientRequest._req.on (file:///C:/Users/USUARIO/AppData/Local/Programs/vessel/resources/app.asar/dist/bundle.js:359:1164502)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:522:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:411:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at TLSSocket.Readable.push (_stream_readable.js:136:10)
    at TLSWrap.onread (net.js:560:20)
Ke @ bundle.js:1


Vessel v0.27
sorry for my bad english, im spanish

**Comment by aaroncox** [comment]
@GATOQSECOMIO - I believe in this case it was again the remote server being offline. If you were using wallet.steem.ws or anything related to that, it had a brief outage right around the time you reported this. Is all working again I assume?
